repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: detect-private-key

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
    - id: gitleaks

  - repo: local
    hooks:
    - id: gosec
      name: Run gosec security scan
      entry: gosec -severity high ./...
      language: system
      pass_filenames: false

  # - repo: local
  #   hooks:
  #   - id: test
  #     name: run unit tests
  #     entry: go test ./...
  #     language: system
  #     pass_filenames: false
